### ISSUE TITLE
Signs randomly disappearing

### ISSUE THREAD

**Issue by tobiazsh** [tobiazsh/myworld_traffic_addition#12]
Signs are randomly disappearing. Fix unknown.

**Comment by tobiazsh** [comment]
Error: ```[21:43:57] [Server thread/ERROR] (Minecraft) Failed to load data for block entity myworld_traffic_addition:customizable_sign_block
 java.lang.IllegalStateException: There is no OpenGL context current in the current thread.
	at knot/org.lwjgl.opengl.GL.createCapabilities(GL.java:384) ~[lwjgl-opengl-3.3.4.jar:?]
	at knot/org.lwjgl.opengl.GL.createCapabilities(GL.java:313) ~[lwjgl-opengl-3.3.4.jar:?]
	at knot/org.lwjgl.opengl.GL.createCapabilities(GL.java:297) ~[lwjgl-opengl-3.3.4.jar:?]
	at knot/at.tobiazsh.myworld.traffic_addition.Utils.Texture.loadTexture(Texture.java:40) ~[main/:?]
	at knot/at.tobiazsh.myworld.traffic_addition.Utils.Textures.smartRegisterTexture(Textures.java:60) ~[main/:?]
	at knot/at.tobiazsh.myworld.traffic_addition.Utils.Elements.ImageElement.loadTexture(ImageElement.java:63) ~[main/:?]
	at knot/at.tobiazsh.myworld.traffic_addition.Utils.SignStyleJson.deconstructElementsToArray(SignStyleJson.java:262) ~[main/:?]
	at knot/at.tobiazsh.myworld.traffic_addition.components.BlockEntities.CustomizableSignBlockEntity.updateTextureVars(CustomizableSignBlockEntity.java:61) ~[main/:?]
	at knot/at.tobiazsh.myworld.traffic_addition.components.BlockEntities.CustomizableSignBlockEntity.readNbt(CustomizableSignBlockEntity.java:220) ~[main/:?]
	at knot/net.minecraft.block.entity.BlockEntity.read(BlockEntity.java:86) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.block.entity.BlockEntity.method_17897(BlockEntity.java:195) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
	at knot/net.minecraft.block.entity.BlockEntity.createFromNbt(BlockEntity.java:193) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.world.chunk.SerializedChunk.method_61797(SerializedChunk.java:568) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.world.chunk.WorldChunk.loadEntities(WorldChunk.java:492) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.world.chunk.ChunkGenerating.method_60553(ChunkGenerating.java:146) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1768) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java) ~[?:?]
	at knot/net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:164) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.executeTask(ServerChunkManager.java:602) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:138) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.runTask(ServerChunkManager.java:611) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:147) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.runTasks(ServerChunkManager.java:575) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.server.world.ServerChunkManager.getChunk(ServerChunkManager.java:151) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.world.World.getChunk(World.java:208) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.world.WorldView.getChunk(WorldView.java:151) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.world.World.getChunk(World.java:202) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.world.World.getWorldChunk(World.java:197) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.world.World.getFluidState(World.java:386) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.entity.Entity.updateSubmergedInWaterState(Entity.java:1534) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.entity.Entity.baseTick(Entity.java:531) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.entity.LivingEntity.baseTick(LivingEntity.java:418) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.entity.Entity.tick(Entity.java:504) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.entity.LivingEntity.tick(LivingEntity.java:2556) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity.java:316) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity.java:757) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.server.network.ServerPlayNetworkHandler.tick(ServerPlayNetworkHandler.java:276) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.network.ClientConnection.tick(ClientConnection.java:401) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo.java:176) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.server.MinecraftServer.tickNetworkIo(MinecraftServer.java:1100) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:1080) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:953) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:114) ~[minecraft-clientOnly-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:713) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292) ~[minecraft-common-c6ffe69074-1.21.3-net.fabricmc.yarn.1_21_3.1.21.3+build.2-v2.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]```

**Comment by tobiazsh** [comment]
Fixed! YAAY! Most annoying bug ever is FINALLY fixed. Issue was: Server was trying to register texture on itself while updating the NBT variables, which of course shouldn't happen as texture registrations are only expected to execute on client.

That being done, fix will be up next version!

**Comment by tobiazsh** [comment]
Fixed!
